In [4]:
import numpy as np

<h2>Problem - 1: Array Creation</h2>
<p>
    Complete the following tasks:
</p>
<ol>
    <li>Initialize an empty array with size 2X2.</li>
    <li>Initialize an all-one array with size 4X2.</li>
    <li>Return a new array of given shape and type, filled with a specified value. <br>
        <b>Hint:</b> Use <code>np.full</code>.
    </li>
    <li>Return a new array of zeros with the same shape and type as a given array. <br>
        <b>Hint:</b> Use <code>np.zeros_like</code>.
    </li>
    <li>Return a new array of ones with the same shape and type as a given array. <br>
        <b>Hint:</b> Use <code>np.ones_like</code>.
    </li>
    <li>Convert an existing list, <code>new_list = [1, 2, 3, 4]</code>, into a NumPy array. <br>
        <b>Hint:</b> Use <code>np.array()</code>.
    </li>
</ol>


In [14]:
# Qn1. Initialize an empty array with size 2X2.
empty_array = np.empty((2, 2))
print("Qn 1 :-")
print("Empty array of size(2x2):\n", empty_array)
print("-----------------------------------------")

# Qn2. Initialize an all-one array with size 4X2.
ones_array = np.ones((4, 2))
print("\nQn 2 :-")
print("All-one array of size(4x2):\n", ones_array)
print("-----------------------------------------")

# Qn3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
filled_array = np.full((4, 4), fill_value=6)
print("\nQn 3 :-")
print("Array filled with 7:\n", filled_array)
print("-----------------------------------------")

# Qn4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
reference_array = np.array([[5, 3], [2, 7], [6, 9]])
zeros_like_array = np.zeros_like(reference_array)
print("\nQn 4 :-")
print("Zeros like reference array:\n", zeros_like_array)
print("-----------------------------------------")

# Qn5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
ones_like_array = np.ones_like(reference_array)
print("\nQn 5 :-")
print("Ones like reference array:\n", ones_like_array)
print("-----------------------------------------")

# Qn6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nQn 6 :-")
print("Converted numpy array:", numpy_array)
print("-----------------------------------------")


Qn 1 :-
Empty array of size(2x2):
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
-----------------------------------------

Qn 2 :-
All-one array of size(4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
-----------------------------------------

Qn 3 :-
Array filled with 7:
 [[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
-----------------------------------------

Qn 4 :-
Zeros like reference array:
 [[0 0]
 [0 0]
 [0 0]]
-----------------------------------------

Qn 5 :-
Ones like reference array:
 [[1 1]
 [1 1]
 [1 1]]
-----------------------------------------

Qn 6 :- 
-------
Converted numpy array: [1 2 3 4]
-----------------------------------------


<h2>Problem - 2: Array Manipulation</h2>
<p>
    Numerical Ranges and Array Indexing:
</p>
<ol>
    <li>
        Create an array with values ranging from 10 to 49. <br>
        <b>Hint:</b> Use <code>np.arange()</code>.
    </li>
    <li>
        Create a 3X3 matrix with values ranging from 0 to 8. <br>
        <b>Hint:</b> Use <code>np.reshape()</code>.
    </li>
    <li>
        Create a 3X3 identity matrix. <br>
        <b>Hint:</b> Use <code>np.eye()</code>.
    </li>
    <li>
        Create a random array of size 30 and find the mean of the array. <br>
        <b>Hint:</b> Use <code>np.random.random()</code> and <code>array.mean()</code>.
    </li>
    <li>
        Create a 10X10 array with random values and find the minimum and maximum values.
    </li>
    <li>
        Create a zero array of size 10 and replace the 5th element with 1.
    </li>
    <li>
        Reverse an array <code>arr = [1, 2, 0, 0, 4, 0]</code>.
    </li>
    <li>
        Create a 2D array with 1 on the border and 0 inside.
    </li>
    <li>
        Create an 8X8 matrix and fill it with a checkerboard pattern.
    </li>
</ol>


In [23]:
# Qn1. An array with values ranging from 10 to 49.
array_range = np.arange(10, 50)
print("Qn 1 :-")
print("Array with values from 10 to 49:\n", array_range)
print("--------------------------------------------------------------------")

# Qn2. A 3X3 matrix with values ranging from 0 to 8.
reshaped_matrix = np.arange(9).reshape((3, 3))
print("\nQn 2 :-")
print("3x3 matrix with values 0 to 8:\n", reshaped_matrix)
print("--------------------------------------------------------------------")

# Qn3. A 3X3 identity matrix.
identityMatrix = np.eye(3)
print("\nQn 3 :-")
print("3x3 Identity matrix:\n", identityMatrix)
print("--------------------------------------------------------------------")

# Qn4. A random array of size 30 and find the mean of the array.
random_array = np.random.random(30)
mean_array_value = random_array.mean()
print("\nQn 4 :-")
print("Random array of size 30:\n", random_array)
print("Mean value of random array:", mean_array_value)
print("--------------------------------------------------------------------")

# Qn5. A 10X10 array with random values and find the minimum and maximum values.
rand = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\nQn 5 :-")
print("10x10 random array:\n", rand)
print("Minimum value:", min_value)
print("Maximum value:", max_value)
print("--------------------------------------------------------------------")

# Qn6. A zero array of size 10 and replace the 5th element with 1.
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nQn 6 :-")
print("Zero array with 5th element replaced with 1:\n", zero_array)
print("--------------------------------------------------------------------")

# Qn7. An reverse array for arr = [1,2,0,0,4,0].
arr = [1, 2, 0, 0, 4, 0]
reversed_array = np.array(arr)[::-1]
print("\nQn 7 :-")
print("Reversed array:", reversed_array)
print("--------------------------------------------------------------------")

# Qn8. A 2D array with 1 on the border and 0 inside.
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\nQn 8 :-")
print("2D array with border 1 and inside 0:\n", border_array)
print("--------------------------------------------------------------------")

# Qn9. An 8X8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\nQn 9 :-")
print("8x8 Checkerboard pattern:\n", checkerboard)
print("--------------------------------------------------------------------")

Qn 1 :-
Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
--------------------------------------------------------------------

Qn 2 :-
3x3 matrix with values 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------------------------------------------------------

Qn 3 :-
3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------------------------------------------------------------

Qn 4 :-
Random array of size 30:
 [0.73302588 0.58211939 0.18521136 0.8730099  0.66778817 0.87463328
 0.04045718 0.0683636  0.49813279 0.72074079 0.39291643 0.00376473
 0.40974659 0.12978532 0.47078644 0.00563818 0.93075525 0.51131608
 0.021468   0.39243972 0.96049835 0.07168043 0.9199412  0.36766319
 0.3437865  0.13093884 0.01801727 0.56270989 0.59704405 0.052527  ]
Mean of random array: 0.41789686018538946
--------------------------------------------------------------------

Qn 5 :-


<h2>Problem - 3: Array Operations</h2>
<p>
    For the following arrays:
</p>
<pre>
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
</pre>
<p>
    Complete all the tasks using NumPy:
</p>
<ol>
    <li>Add the two arrays.</li>
    <li>Subtract the two arrays.</li>
    <li>Multiply the array with any integer of your choice.</li>
    <li>Find the square of each element of the array.</li>
    <li>Find the dot product between:
        <ul>
            <li><code>v</code> and <code>w</code></li>
            <li><code>x</code> and <code>v</code></li>
            <li><code>x</code> and <code>y</code></li>
        </ul>
    </li>
    <li>Concatenate <code>x</code> and <code>y</code> along rows and concatenate <code>v</code> and <code>w</code> along columns. <br>
        <b>Hint:</b> Use <code>np.concatenate()</code> or <code>np.vstack()</code> functions.
    </li>
    <li>Concatenate <code>x</code> and <code>v</code>. If you encounter an error, observe and explain why it occurred.</li>
</ol>

In [8]:
# Array defined in question
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Qn1. Adding the two arrays
array_sum = x + y
print("Qn 1 :-")
print("Array Addition:\n", array_sum)
print("-----------------------------------------")

# Qn2. Subtracting the two arrays
array_diff = x - y
print("\nQn 2 :-")
print("Array Subtraction:\n", array_diff)
print("-----------------------------------------")

# Qn3. Multiplying  the array with any integer (e.g., multiply x by 3)
array_mul = x * 3
print("\nQn 3 :-")
print("Array Multiplication:\n", array_mul)
print("-----------------------------------------")

# Qn4. Finding the square of each element of the array
array_square = np.square(x)
print("\nQn 4 :-")
print("Array Squared:\n", array_square)
print("-----------------------------------------")

# Qn5. Finding the dot product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nQn 5 :-")
print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)
print("-----------------------------------------")

# Qn6. Concatenate x and y along rows; Concatenate v and w along columns
concat_xy = np.concatenate((x, y), axis=0)
concat_vw = np.vstack((v, w))
print("\nQn 6 :-")
print("Concatenation of x and y along rows:\n", concat_xy)
print("Concatenation of v and w along columns:\n", concat_vw)
print("-----------------------------------------")

# Qn7. Concatenate x and v; observe error if occurs and explains the error
print("\nQn 7 :-")
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenation of x and v:\n", concat_xv)
    print("-----------------------------------------")
except ValueError as e:
    print("Error:", e)
    print("\nExplanation: Here, NumPy tries to stack x and v row-wise , so both arrays must have the same number of columns. \nx has 2 columns, but v, being a 1D array (As it has only one row), doesn't naturally have a second dimension")
    print("-----------------------------------------")


Qn 1 :-
Array Addition:
 [[ 6  8]
 [10 13]]
-----------------------------------------

Qn 2 :-
Array Subtraction:
 [[-4 -4]
 [-4 -3]]
-----------------------------------------

Qn 3 :-
Array Multiplication:
 [[ 3  6]
 [ 9 15]]
-----------------------------------------

Qn 4 :-
Array Squared:
 [[ 1  4]
 [ 9 25]]
-----------------------------------------

Qn 5 :-
Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
-----------------------------------------

Qn 6 :-
Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]
-----------------------------------------

Qn 7 :-
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Explanation: Here, NumPy tries to stack x and v row-wise , so both arrays must have the same number of columns. 
x has 2 columns, but v, being a 1D 

<h2>Problem - 4: Matrix Operations</h2>
<p>
    For the following arrays:
</p>
<pre>
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
</pre>
<p>
    Prove the following with NumPy:
</p>
<ol>
    <li>Prove <code>A.A⁻¹ = I</code>.</li>
    <li>Prove <code>AB ≠ BA</code>.</li>
    <li>Prove <code>(AB)<sup>T</sup> = B<sup>T</sup>A<sup>T</sup></code>.</li>
</ol>
<p>
    Solve the following system of linear equations using inverse methods:
</p>
<pre>
2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9
</pre>
<ol>
    <li>
        Represent the equations in matrix form using a NumPy array.
    </li>
    <li>
        Solve for <code>AX = B</code>.
    </li>
    <li>
        Solve the equations using <code>np.linalg.inv</code> function. <br>
        <b>Hint:</b> Explore more about the <code>linalg</code> module in NumPy.
    </li>
</ol>

In [10]:
# Define matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A⁻¹ = I
A_inverse = np.linalg.inv(A)       # Inverse of A
identity_matrix = np.dot(A, A_inverse)
print("Qn 1 :-")
print("A.A⁻¹ = I:\n", identity_matrix)
print("Prove A.A⁻¹ = I: ", np.array_equal(identity_matrix, np.eye(2)))
print("-----------------------------------------")

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nQn 2 :-")
print("AB:\n", AB)
print("BA:\n", BA)
print("Prove AB ≠ BA: ", not np.array_equal(AB, BA))
print("-----------------------------------------")

# 3. Prove (AB)ᵀ = BᵀAᵀ
AB_T = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("\nQn 3 :-")
print("(AB)ᵀ:\n", AB_T)
print("BᵀAᵀ:\n", BT_AT)
print("Prove (AB)ᵀ = BᵀAᵀ: ", np.array_equal(AB_T, BT_AT))
print("-----------------------------------------")

# Solve the linear system using inverse methods
# System of equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Represent the system as AX = B
coeff_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
rhs_vector = np.array([-1, -3, 9])

# Solve for X using np.linalg.inv
coeff_matrix_inv = np.linalg.inv(coeff_matrix)
solution = np.dot(coeff_matrix_inv, rhs_vector)
print("\nSolution to the system using inverse methods:\n", solution)
print("-----------------------------------------")

# Alternative: Use np.linalg.solve (more efficient)
solution_alt = np.linalg.solve(coeff_matrix, rhs_vector)
print("\nSolution to the system using np.linalg.solve function:\n", solution_alt)
print("-----------------------------------------")


Qn 1 :-
A.A⁻¹ = I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Prove A.A⁻¹ = I:  False
-----------------------------------------

Qn 2 :-
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Prove AB ≠ BA:  True
-----------------------------------------

Qn 3 :-
(AB)ᵀ:
 [[23 51]
 [13 29]]
BᵀAᵀ:
 [[23 51]
 [13 29]]
Prove (AB)ᵀ = BᵀAᵀ:  True
-----------------------------------------

Solution to the system using inverse methods:
 [ 2.  1. -2.]
-----------------------------------------

Solution to the system using np.linalg.solve function:
 [ 2.  1. -2.]
-----------------------------------------
